version: '3'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PASS}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: consumer
    env_file:
      - .env
    networks:
      - default
    ports:
      - "5000:5000"
    # depends_on:
    #   postgres:
    #     condition: service_healthy
networks:
  default:
    name: lab_2
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
volumes:
  postgres_data:

